#!/bin/sh

# Tests stopping of a circular move

title=`basename $0`
cd `dirname $0`/../bin

cat << EOF | ./gotestsh -t 0.01 -n 1 > outxy
tpar 1 2 7
linear
pos
movew 0 0 0 0 0 0
movec -1 1 0 0 0 0   0 1 0   0 0  1   0
movew 0 0 0 0 0 0
run
EOF

cat << EOF | ./gotestsh -t 0.01 -n 1 > outstop
tpar 1 2 7
linear
pos
movew 0 0 0 0 0 0
movec -1 1 0 0 0 0   0 1 0   0 0  1   0
run 200
stop
movew 0 0 0 0 0 0
run
EOF

cat << EOF | ./gotestsh -t 0.01 -n 1 > outvel
tpar 1 2 7
linear
vel
movew 0 0 0 0 0 0
movec -1 1 0 0 0 0   0 1 0   0 0  1   0
run 200
stop
movew 0 0 0 0 0 0
run
EOF

echo "set title '$title' ; set size ratio -1 ; plot 'outxy' using 2:3 title 'XY'" | gnuplot -persist

echo "set title '$title' ; set size ratio -1 ; plot 'outstop' using 2:3 title 'XY Stopping'" | gnuplot -persist

echo "set title '$title' ; plot 'outvel' using 1:2 title 'X Speed Stopping', '' using 1:3 title 'Y Speed Stopping'" | gnuplot -persist

cat <<EOF
This shows circular motion for three-quarters of a turn in one plot, a
plot of motion stopped partway around, and a plot of the speeds during
stopping.
Hit 'q' to quit the displays, 'ENTER' to continue...
EOF
read input

exit 0
