#!/bin/sh

# Tests stopping

title=`basename $0`
cd `dirname $0`/../bin

cat << EOF | ./gotestsh -t 0.01 -n 1 > out
par 1 1 2 7
par 2 1 20 7
par 3 1 2 70
par 4 1 1 0.1
par 5 1 0.1 1
par 6 1 0.1 0.1
linear
vel
movej 0 0 0 0 0 0
movej 0.9 2.2 3.3 4.4 5.5 6.6
run 100
stop
run
run
run
run
run
EOF

echo "set title '$title' ; plot 'out' using 1:2 with linespoints title 'Joint 1', '' using 1:3 with linespoints title 'Joint 2', '' using 1:4 with linespoints title 'Joint 3', '' using 1:5 with linespoints title 'Joint 4', '' using 1:6 with linespoints title 'Joint 5', '' using 1:7 with linespoints title 'Joint 6'" | gnuplot -persist

cat <<EOF
This shows position v. time of joint jogging with an intervening stop.
Hit 'q' to quit the displays, 'ENTER' to continue...
EOF
read input

exit 0
