#!/bin/sh

# Shows pos, no subinterpolation, for some circular moves
# format is 13 numbers:
# movec end-x y z r p w center-x y z normal-x y z turns

title=`basename $0`
cd `dirname $0`/../bin

cat << EOF | ./gotestsh -t 0.1 -n 1 > out
tpar 1 2 7
linear
pos
movew 0 0 1 0 0 0
movec 0 2 1 10 0 0     0 1 1   0 0  1   0
movec 1 3 1 10 -15 0   0 3 1   0 0 -1   0
movec 2 2 1 10 -15 20  2 3 1   0 0  1   0
movec 0 0 1 0 0 0      2 0 1   0 0 -1   0
run
EOF

echo "set title '$title' ; set size ratio -1 ; plot 'out' using 2:3 title 'XY'" | gnuplot -persist

echo "set title '$title' ; plot 'out' using 1:2 title 'X', '' using 1:3 title 'Y', '' using 1:5 title 'Roll', '' using 1:6 title 'Pitch', '' using 1:7 title 'Yaw'" | gnuplot -persist

cat <<EOF
This shows circular motion around a schmoo-shaped path in one plot,
and position v. time of XYZ RPW in the second plot.
Hit 'q' to quit the displays, 'ENTER' to continue...
EOF
read input

exit 0
