#!/bin/sh

# Tests time-based moves

title=`basename $0`
cd `dirname $0`/../bin

cat << EOF | ./gotestsh -t 0.01 -n 1 > out
tpar 10 10 100
rpar 10 30 90
linear
pos
movew 0 0 0 0 0 0
movew 15 -30 45 10 -20 60
time 10
movew 0 0 0 0 0 0
notime
run
EOF

echo "set title '$title' ; plot 'out' using 1:2 with linespoints title 'X', '' using 1:3 with linespoints title 'Y', '' using 1:4 with linespoints title 'Z', '' using 1:5 with linespoints title 'Roll', '' using 1:6 with linespoints title 'Pitch', '' using 1:7 with linespoints title 'Yaw'" | gnuplot -persist

cat <<EOF
This tests time-based moves.
Hit 'q' to quit the displays, 'ENTER' to continue...
EOF
read input

exit 0
