#!/bin/sh

# Tests stopping

title=`basename $0`
cd `dirname $0`/../bin

cat << EOF | ./gotestsh -t 0.01 -n 1 > out
par 1 1.1 2.1 7.1
par 2 1.2 2.2 7.2
par 3 1.3 2.3 7.3
par 4 14 2.4 7.4
par 5 15 2.5 7.5
par 6 16 2.6 7.6
linear
vel
moveuj 1 2 3 4 5 6
moveuj 2 6 9 12 15 18
run 200
stop
run
run
run
run
run
EOF

echo "set title '$title' ; plot 'out' using 1:2 with linespoints title 'Joint 1', '' using 1:3 with linespoints title 'Joint 2', '' using 1:4 with linespoints title 'Joint 3', '' using 1:5 with linespoints title 'Joint 4', '' using 1:6 with linespoints title 'Joint 5', '' using 1:7 with linespoints title 'Joint 6'" | gnuplot -persist

cat <<EOF
This shows speed v. time plots of uncoordinated joint motion.
Hit 'q' to quit the displays, 'ENTER' to continue...
EOF
read input

exit 0
